[tool.poetry]
name = "label-v2"
version = "0.1.0"
description = ""
authors = ["BlackDP <blackdp@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
