# Generated by Django 5.0.1 on 2024-01-31 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Вид цены')),
            ],
            options={
                'verbose_name': 'Вид цены',
                'verbose_name_plural': 'Виды цен',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.pricetype', verbose_name='Вид цены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'unique_together': {('price_type', 'product')},
            },
        ),
    ]
